[build]
  publish = "."  # This means: deploy the current folder

# HTTP headers to force browsers to always load fresh content
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
